FROM node:20 AS dev
WORKDIR /app

# Install dependencies first
COPY frontend/package*.json ./
RUN npm install

# Copy the rest of the Angular source
COPY frontend .

EXPOSE 4200

# Run Angular dev server with hot reload
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"]
